plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nexvary.metasecuritylab'
    compileSdk 35

    defaultConfig {
        applicationId 'com.nexvary.metasecuritylab'
        minSdk 24
        targetSdk 35
        versionCode 80
        versionName '1.80.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
